In [1]:
# 정수형 series 
import pandas as pd
s= pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [2]:
# 실수형 series
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [3]:
# 인덱스 지정
s = pd.Series([1.3,2.5,3.6,2.3,1.2], index=['a','b','c','d','e'])
print(s)

a    1.3
b    2.5
c    3.6
d    2.3
e    1.2
dtype: float64


In [4]:
import numpy as np
a = np.array([1,2,3])
print(a)

b = np.zeros(5)
print(b)

c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a,b))
# 요소별 곱
print(np.multiply(a,b))
# 요소별 평균
print(np.mean(a))

[5 5 5 5]
[4 6 6 4]
2.5


In [6]:
# 0 과 1 사이에서 균일한 분포를 갖는 숫자 샘플링
a = np.random.rand(2,5)
print(a)

# 표준정규분포를 갖는 숫자들 샘플링
b = np.random.rand(2,4)
print(b)

[[0.16161898 0.67763389 0.16549167 0.72277789 0.03826262]
 [0.34336911 0.14926012 0.86604472 0.57188346 0.23728906]]
[[0.63966008 0.31671434 0.58812184 0.68109654]
 [0.40686817 0.48523077 0.93270409 0.99271528]]


In [7]:
# 파이
a = np.pi
print(a)
# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [8]:
a = np.array([1,2,5,6,8])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[1 2 5 6 8]
int32


In [9]:
a = np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
# 타입 지정
a = np.array([[1,2,3],[4,5,6]],dtype=complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [11]:
a = np.zeros(10)
print(a)
print(np.ones((2,3,4), dtype = np.int16))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [12]:
no = [1,2,3]
sn = []
sn.append('수학')
sn.append('과학')
sn.append('파이썬')

In [17]:
su = pd.DataFrame()
su['과목번호'] = no
su['과목명'] = sn
print(su)
su.to_excel("C:\\Users\\hee\\Desktop\\Python\\python2\\day05\\subject.xlsx", index=False)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


In [18]:
su.to_csv("C:\\Users\\hee\\Desktop\\Python\\python2\\day05\\subject.csv", encoding='utf-8-sig',index=False)

In [19]:
# 데이터 프레임은 파이썬의 리스트와 딕셔너리의 조합이다.
df = pd.DataFrame({"이름":["홍길동","홍길순","임꺽정"],"age":[20,21,22],"성별":["male","female","male"]})
print(df)

    이름  age      성별
0  홍길동   20    male
1  홍길순   21  female
2  임꺽정   22    male


In [20]:
# 데이터프레임에 시리즈 추가
home = pd.Series(["서울","부산","대전"],name = "고향")
df["고향"] = home
print(df)

    이름  age      성별  고향
0  홍길동   20    male  서울
1  홍길순   21  female  부산
2  임꺽정   22    male  대전


In [21]:
# 집계함수
# 평균, 최대값, 최솟값
print(df["age"].mean())
print(df["age"].max())
print(df["age"].min())

21.0
22
20


In [22]:
# 데이터 프레임의 기본 통계 내용 출력
print(df.describe())

        age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0


In [23]:
# head는 위에서부터 데이터를 끊어옴
print(df.head(2))

    이름  age      성별  고향
0  홍길동   20    male  서울
1  홍길순   21  female  부산


In [24]:
# tail은 밑에서부터 데이터를 끊어옴
print(df.tail(2))

    이름  age      성별  고향
1  홍길순   21  female  부산
2  임꺽정   22    male  대전
